version: "3.8"

services:
  mongodb:
    image: mongo:4.4.18
    container_name: vividi-mongodb
    restart: unless-stopped
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - vividinet

  server:
    image: xprss/v2d-backend:${VERSION:-latest}
    container_name: v2d-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 8000
      MONGO_URI: mongodb://root:example@mongodb:27017/vividi?authSource=admin
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
      - vividinet

  client:
    image: xprss/v2d-frontend:${VERSION:-latest}
    container_name: v2d-frontend
    restart: unless-stopped
    ports:
      - "3000:80" # assuming NGINX serves Angular at port 80 inside container
    depends_on:
      - server
    networks:
      - vividinet

networks:
  vividinet:
    driver: bridge
