/**
 * Vividi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';



import { Configuration }                                     from '../configuration';



export interface HeartbeatServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param body 
     */
    heartbeatControllerCreate(body: object, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    heartbeatControllerFindAll(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    heartbeatControllerFindOne(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    heartbeatControllerRemove(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     * @param body 
     */
    heartbeatControllerUpdate(id: string, body: object, extraHttpRequestParams?: any): Observable<{}>;

}
