/**
 * Vividi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateUserDto } from '../model/models';
import { UpdateUserDto } from '../model/models';
import { UserControllerCatFoundRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface UserServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param userControllerCatFoundRequest 
     */
    userControllerCatFound(userControllerCatFoundRequest: UserControllerCatFoundRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param createUserDto 
     */
    userControllerCreate(createUserDto: CreateUserDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    userControllerFindAll(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param email 
     */
    userControllerFindOne(email: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    userControllerLogin(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    userControllerRemove(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     * @param updateUserDto 
     */
    userControllerUpdate(id: string, updateUserDto: UpdateUserDto, extraHttpRequestParams?: any): Observable<{}>;

}
