/**
 * Vividi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateVibeDto } from '../model/models';
import { UpdateVibeDto } from '../model/models';
import { VibeControllerCreatePictureRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface VibeServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param createVibeDto 
     */
    vibeControllerCreate(createVibeDto: CreateVibeDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param vibeControllerCreatePictureRequest 
     */
    vibeControllerCreatePicture(vibeControllerCreatePictureRequest: VibeControllerCreatePictureRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    vibeControllerFindAll(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    vibeControllerFindOne(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id The id of the Vibe
     */
    vibeControllerGetImage(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    vibeControllerRemove(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id The id of the Vibe
     * @param updateVibeDto 
     */
    vibeControllerUpdate(id: string, updateVibeDto: UpdateVibeDto, extraHttpRequestParams?: any): Observable<{}>;

}
