/**
 * Vividi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateUserDto { 
    /**
     * The user\'s first name
     */
    firstName: string;
    /**
     * The user\'s last name
     */
    lastName: string;
    /**
     * The user\'s email
     */
    email: string;
}

