/**
 * Vividi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateVibeDto { 
    /**
     * The userId of the user creating the vibe
     */
    userId: string;
    /**
     * The user full name of the user creating the vibe
     */
    userFullName: string;
    /**
     * The description for the vibe
     */
    description: string;
    /**
     * The moment classifying the vibe
     */
    moment: CreateVibeDto.MomentEnum;
    /**
     * The reference to the file in the storage
     */
    fileId: string;
}
export namespace CreateVibeDto {
    export const MomentEnum = {
        PreviousDays: 'PREVIOUS_DAYS',
        Ceremony: 'CEREMONY',
        Lunch: 'LUNCH',
        FollowingDays: 'FOLLOWING_DAYS'
    } as const;
    export type MomentEnum = typeof MomentEnum[keyof typeof MomentEnum];
}


