/**
 * Vividi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LikeVibeDto { 
    /**
     * The userId of the user liking the vibe
     */
    userId: string;
    /**
     * The id of the vibe being liked
     */
    vibeId: string;
    /**
     * Indicates whether the vibe is liked or not
     */
    isLiked: boolean;
}

