name: Vividi build
run-name: ${{github.actor}} is building Vividi.
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔨 Build started!"
      - name: Build frontend
        run: cd frontend; npm run build;
      - name: Build backend
        run: |
          cd ../backend; npm run build;
