name: CD Build and Release Workflow

on:
  push:
    branches:
      - stable

permissions:
  contents: write

jobs:
  build:
    name: Build and push images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: stable

      - name: Set up actions bot identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout stable

      - name: Set up Python and bump2version
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install bump2version
        run: pip install bump2version

      - name: Bump patch version
        run: bump2version patch

      - name: Set VERSION env variable
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Push version tag
        run: git push --follow-tags

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Frontend (Angular)
      - name: Build and push v2d-frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/v2d-frontend:${{ env.VERSION }}

      # Backend (NestJS)
      - name: Build and push v2d-backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/v2d-backend:${{ env.VERSION }}
