name: CD Build and Release Workflow

on:
  push:
    branches:
      - stable

permissions:
  contents: write

jobs:
  build:
    name: Build and push images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Frontend (Angular)
      - name: Build and push v2d-frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/v2d-frontend:latest

      # Backend (NestJS)
      - name: Build and push v2d-backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/v2d-backend:latest