name: Build tag and Release it

on:
  push:
    tags:
      - "v*" # Runs when a tag like "v1.0.0" is pushed
  workflow_dispatch:
    inputs:
      version:
        description: Release version
        required: true

permissions:
  contents: write

jobs:
  build:
    name: Build Angular & NestJS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Install and build Frontend (Angular)
      - name: Install dependencies (Frontend)
        run: cd frontend && npm install

      - name: Build Angular
        run: cd frontend && npm run build --prod

      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/dist/

      # Install and build Backend (NestJS)
      - name: Install dependencies (Backend)
        run: cd backend && npm install

      - name: Build NestJS
        run: cd backend && npm run build

      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-build
          path: backend/dist/

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Frontend Artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: frontend-build

      - name: Release frontend
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.version }}
          release_name: vividi-frontend:${{ inputs.version }}
          body: "Automated release for vividi-frontend"
          draft: false
          prerelease: false
          
      - name: Download Backend Artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-build
          path: backend-build
          
      - name: Release backend
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.version }}
          release_name: vividi-backend:${{ inputs.version }}
          body: "Automated release for vividi-backend"
          draft: false
          prerelease: false
