name: Build, Tag, and Release

on:
  push:
    tags:
      - "v*"  # Trigger when a tag like v1.0.0 is pushed
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g., 1.0.0)"
        required: true
      description:
        description: "Release description"
        required: true

permissions:
  contents: write

jobs:
  build:
    name: Build Angular & NestJS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Frontend (Angular)
      - name: Install dependencies (Frontend)
        run: cd frontend && npm install

      - name: Build Angular
        run: cd frontend && npm run build --prod

      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/dist/

      # Backend (NestJS)
      - name: Install dependencies (Backend)
        run: cd backend && npm install

      - name: Build NestJS (with more heap)
        run: node --max-old-space-size=2048 ./node_modules/.bin/nest build
        working-directory: backend

      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-build
          path: backend/dist/

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Frontend Artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: frontend-build

      - name: Download Backend Artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-build
          path: backend-build

      - name: Zip Frontend Build
        run: |
          cd frontend-build
          zip -r ../frontend-build.zip .
          cd ..

      - name: Zip Backend Build
        run: |
          cd backend-build
          zip -r ../backend-build.zip .
          cd ..

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version || github.ref_name }}
          release_name: vividi-v${{ github.event.inputs.version || github.ref_name }}
          body: ${{ github.event.inputs.description || 'Release created from tag' }}
          draft: false
          prerelease: false

      - name: Upload Frontend Artifact to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./frontend-build.zip
          asset_name: frontend-build.zip
          asset_content_type: application/zip

      - name: Upload Backend Artifact to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./backend-build.zip
          asset_name: backend-build.zip
          asset_content_type: application/zip
